In [63]:
%matplotlib
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn

Using matplotlib backend: Qt5Agg


In [18]:
from sklearn.datasets import load_boston
boston = load_boston()

In [19]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [21]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [25]:
boston.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [26]:
bos = pd.DataFrame(boston.data),

In [28]:
bos.head(5)

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [29]:
bos.columns = boston.feature_names
bos.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [31]:
boston.target[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [32]:
bos['PRICE'] = boston.target

In [34]:
bos.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [41]:
from sklearn.linear_model import LinearRegression
X = bos.drop('PRICE',axis = 1)

lm = LinearRegression()
lm


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [43]:
lm.fit(X,bos.PRICE)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [46]:
print('Intercept coefficient is',lm.intercept_)

Intercept coefficient is 36.45948838509015


In [48]:
print("No of coeff",len(lm.coef_))

No of coeff 13


In [57]:
pd.DataFrame(list(zip(X.columns, lm.coef_)), columns = ['features','estimatedCoefficients'])

features  estimatedCoefficients
0      CRIM              -0.108011
1        ZN               0.046420
2     INDUS               0.020559
3      CHAS               2.686734
4       NOX             -17.766611
5        RM               3.809865
6       AGE               0.000692
7       DIS              -1.475567
8       RAD               0.306049
9       TAX              -0.012335
10  PTRATIO              -0.952747
11        B               0.009312
12    LSTAT              -0.524758

In [68]:
Prediction = lm.predict(X)

In [69]:
Prediction

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211,
       18.99949651, 21.58679568, 20.90652153, 19.55290281, 19.28348205,
       19.29748321, 20.52750979, 16.91140135, 16.17801106, 18.40613603,
       12.52385753, 17.67103669, 15.83288129, 13.80628535, 15.67833832,
       13.38668561, 15.46397655, 14.70847428, 19.54737285, 20.8764282 ,
       11.45511759, 18.05923295,  8.81105736, 14.28275814, 13.70675891,
       23.81463526, 22.34193708, 23.10891142, 22.91502612, 31.35762569,
       34.21510225, 28.02056414, 25.20386628, 24.60979273, 22.94149176,
       22.09669817, 20.42320032, 18.03655088,  9.10655377, 17.20607751,
       21.28152535, 23.97222285, 27.6558508 , 24.04901809, 15.3618477 ,
       31.15264947, 24.85686978, 33.10919806, 21.77537987, 21.08493555,
       17.8725804 , 18.51110208, 23.98742856, 22.55408869, 23.37308644,
       30.36148358, 25.53056512, 21.11338564, 17.42153786, 20.78

In [70]:
mse = np.mean((bos.PRICE - lm.predict(X)) **2)
mse

21.89483118172922

In [71]:
#pd.DataFrame(Prediction).to_csv('pred.csv')

In [89]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [83]:
print(sklearn.__version__)

0.20.3


In [115]:
X_train,X_test,Y_train,Y_test = train_test_split(X, bos.PRICE,test_size=0.33, random_state = 50)

In [95]:
# print(cross_val_score(lm, X_train, Y_train, cv=3))

[0.70145544 0.7328394  0.72722015]


In [116]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(339, 13)
(339,)
(167, 13)
(167,)


In [117]:
lm = LinearRegression()
lm.fit(X_train, Y_train)
pred_train = lm.predict(X_train)
pred_test = lm.predict(X_test)

In [118]:
print("Fit a model X_train,and calculate MSE with Y_train:",np.mean((Y_train-lm.predict(X_train))**2))

Fit a model X_train,and calculate MSE with Y_train: 17.565993913439996


In [107]:
print("Fit a model X_train,and calculate MSE with Y_train:",np.mean((Y_test-lm.predict(X_test))**2))

Fit a model X_train,and calculate MSE with Y_train: 28.530458765974604


In [119]:
Prediction1 = lm.predict(X_test)

In [120]:
Prediction1

array([10.09345112, 25.18985007, 19.69308437, 27.76966983, 22.29831885,
       23.29882831, 16.39669608, 16.72378225, 12.83255648, 25.10144634,
       14.45397328, 28.62175287, 17.4336047 , 34.26197964, 18.35554019,
       13.49578316, 14.04259579, 28.54698909, 22.35004557, 24.23117695,
       24.02413585, 36.93530496, 30.69211158, 19.09246472, 20.7982339 ,
       16.87054886, 11.39628631, 24.01928004, 30.88593944, 23.68937677,
       20.74218282,  5.93704438, 30.17621625, 36.0942302 , 21.95738604,
       32.11691485, 34.27611841, 20.8016289 , 28.54341212, 39.7497437 ,
       39.67716774, 12.65285693, 20.57820578, 25.40517025,  2.3025087 ,
       14.65204105, 22.35107996, 34.67956889, 25.94239183, 21.78714855,
       30.37726756, 25.21681198, 15.12744182, 20.3991978 , 24.79104325,
       21.49193351, 32.4721243 , 24.87983529, 19.73880504, 19.14305764,
       15.35831864, 20.6174378 , 15.76825177, 23.20242747, 19.92601012,
       19.87429085, 16.14219051, 22.03792982, 25.3477652 , 20.26